version: "3"
services :
  node-app:
    container_name: express-node-app-container
    image:  souayah21/startingwithdocker

    #depends_on : 
    #  - postgres
    #  - redis
    ports :
      - "4001:4001"
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:  swayahmalek6
      MONGO_INITDB_ROOT_PASSWORD: bacscience2021 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on :
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: malek
      ME_CONFIG_MONGODB_ADMINPASSWORD: malek
      ME_CONFIG_MONGODB_URL: mongodb://swayahmalek6:bacscience2021@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  #postgres:
  #  image: postgres
  #  restart: always
  #  volumes:
  #    - postgres-db:/var/lib/postgresql/data
  #  environment:
  #    POSTGRES_USER:  root
  #    POSTGRES_PASSWORD: root 

  redis:
    image : redis 
  ngnix:
    image: nginx:stable-alpine
    ports:
       - "80:80"
    volumes:
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - node-app
    


volumes:
  mongo-db:
  #postgres-db: