version : "3"
services :
  node-app:
    container_name: express-node-app-container
    build : .
    volumes : 
      - ./src:/app/src:ro
    ports:
        - "4001:4001"
    environment :
      - PORT = 4000
      - NODE_ENV=production
    env_file:
      - ./.env